export enum httpStatus {
  // INFORMATIONAL RESPONSE
  "CONTINUE" = 100,
  "SWITCHING_PROTOCOLS" = 101,
  "PROCESSING" = 102,

  // SUCCESS RESPONSES
  "OK" = 200,
  "CREATED" = 201,
  "NO_CONTENT" = 204,

  // REDIRECTION MESSAGES
  "MOVED_PERMANENTLY" = 301,
  "FOUND" = 302,
  "SEE_OTHER" = 303,

  // CLIENT ERROR RESPONSES
  "BAD_REQUEST" = 400,
  "UNAUTHORIZED" = 401,
  "FORBIDDEN" = 403,
  "NOT_FOUND" = 404,
  "CONFLICT" = 409,

  // SERVER ERROR RESPONSES
  "INTERNAL_SERVER_ERROR" = 500,
  "SERVICE_UNAVAILABLE" = 502,
  "GATEWAY_TIMEOUT" = 504,
}
